"use client";
import { useEffect, useMemo, useState } from "react";
import { VideoCardData, compact } from "@/components/video-card";

type Data = { subscribers: number; totalViews: number; videoCount: number; videos: VideoCardData[]; syncedAt: string };
export default function MetricsPage() {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(false);
  async function load() { setError(false); try { const response = await fetch("/api/youtube", { cache: "no-store" }); if (!response.ok) throw new Error(); setData(await response.json()); } catch { setError(true); } }
  useEffect(() => { load(); }, []);
  const categories = useMemo(() => { const counts = new Map<string,number>(); data?.videos.forEach((video) => counts.set(video.category, (counts.get(video.category)||0)+1)); return [...counts.entries()].sort((a,b)=>b[1]-a[1]); }, [data]);
  return <main id="conteudo" className="page-main"><header className="page-hero"><span className="eyebrow-v2">MÉTRICAS PÚBLICAS</span><h1>Os números que podem ser mostrados.</h1><p>Somente dados públicos do canal. Receita, CTR, retenção e informações do YouTube Studio ficam de fora.</p></header>{!data && !error && <div className="metric-loading" aria-label="Carregando métricas"><i/><i/><i/></div>}{error && !data && <div className="empty-state"><strong>Não foi possível atualizar as métricas.</strong><p>O restante do site continua disponível.</p><button onClick={load}>Tentar novamente</button></div>}{data && <><section className="metrics-dashboard"><article><span>Inscritos</span><strong>{compact(data.subscribers)}</strong><small>Contagem pública atual</small></article><article><span>Vídeos publicados</span><strong>{data.videoCount}</strong><small>Catálogo total do canal</small></article><article><span>Visualizações totais</span><strong>{compact(data.totalViews)}</strong><small>Alcance público acumulado</small></article><article><span>Produtos mapeados</span><strong>30+</strong><small>Estimativa editorial em revisão</small></article><article><span>Garimpos catalogados</span><strong>10+</strong><small>Índice editorial em expansão</small></article></section><section className="data-panels"><div><span className="eyebrow-v2">VÍDEOS RECENTES</span><h2>Mais assistidos no recorte</h2><ol>{[...data.videos].sort((a,b)=>b.views-a.views).slice(0,5).map((video,index)=><li key={video.id}><span>0{index+1}</span><div><strong>{video.title}</strong><small>{video.category}</small></div><b>{compact(video.views)}</b></li>)}</ol></div><div><span className="eyebrow-v2">CATEGORIAS PRESENTES</span><h2>Assuntos do canal</h2><div className="category-bars">{categories.map(([category,count])=><div key={category}><span>{category}</span><i><b style={{width:`${(count/Math.max(...categories.map((item)=>item[1]),1))*100}%`}}/></i><strong>{count}</strong></div>)}</div></div></section><p className="sync-note">Última tentativa de sincronização: {new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(data.syncedAt))}. Os números podem ser arredondados pelo próprio YouTube.</p></>}
  </main>;
}
