import { desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { contentEntries, moderationActions } from "@/db/schema";
import { sameOriginRequest, sanitizePlainText } from "@/lib/security";
import { requireAdminApi } from "@/lib/server-auth";
function disabled(){return process.env.ADMIN_ENABLED!=="true";}
export async function GET(){if(disabled())return Response.json({error:"Painel desativado."},{status:503});const auth=await requireAdminApi();if("error" in auth)return auth.error;const entries=await getDb().select().from(contentEntries).orderBy(desc(contentEntries.updatedAt)).limit(100);return Response.json({entries});}
export async function POST(request:Request){if(disabled())return Response.json({error:"Painel desativado."},{status:503});if(!sameOriginRequest(request))return Response.json({error:"Origem inválida."},{status:403});const auth=await requireAdminApi();if("error" in auth)return auth.error;const body=await request.json().catch(()=>({}));const type=sanitizePlainText(body.type,20);const title=sanitizePlainText(body.title,160);const slug=sanitizePlainText(body.slug,100).toLowerCase().replace(/[^a-z0-9-]/g,"-").replace(/-+/g,"-");if(!["review","find","video","category","setting"].includes(type)||title.length<3||slug.length<3)return Response.json({error:"Conteúdo inválido."},{status:400});const now=new Date().toISOString();const entry={id:crypto.randomUUID(),type:type as "review"|"find"|"video"|"category"|"setting",title,slug,payload:JSON.stringify(body.payload||{}),status:"draft" as const,featured:false,authorEmail:auth.user.email,createdAt:now,updatedAt:now};const db=getDb();await db.insert(contentEntries).values(entry);await db.insert(moderationActions).values({id:crypto.randomUUID(),actorEmail:auth.user.email,action:"content.create",targetType:type,targetId:entry.id,reason:null,metadata:JSON.stringify({slug}),createdAt:now});return Response.json({entry},{status:201});}
export async function PATCH(request:Request){if(disabled())return Response.json({error:"Painel desativado."},{status:503});if(!sameOriginRequest(request))return Response.json({error:"Origem inválida."},{status:403});const auth=await requireAdminApi();if("error" in auth)return auth.error;const body=await request.json().catch(()=>({}));const id=sanitizePlainText(body.id,80);if(!id)return Response.json({error:"ID obrigatório."},{status:400});const allowedStatus=["draft","published","archived"] as const;const status=allowedStatus.includes(body.status)?body.status:undefined;const now=new Date().toISOString();const db=getDb();const updated=await db.update(contentEntries).set({status,featured:Boolean(body.featured),updatedAt:now}).where(eq(contentEntries.id,id)).returning();if(!updated.length)return Response.json({error:"Conteúdo não encontrado."},{status:404});await db.insert(moderationActions).values({id:crypto.randomUUID(),actorEmail:auth.user.email,action:"content.update",targetType:updated[0].type,targetId:id,reason:null,metadata:JSON.stringify({status,featured:Boolean(body.featured)}),createdAt:now});return Response.json({entry:updated[0]});}
