import { and, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { communityTopics } from "@/db/schema";
import { communityReplies } from "@/db/schema";
import { sameOriginRequest, validateCommunityPost } from "@/lib/security";
import { requireApiUser } from "@/lib/server-auth";
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){if(process.env.COMMUNITY_ENABLED!=="true")return Response.json({error:"Comunidade em breve."},{status:503});const{id}=await params;const db=getDb();const topics=await db.select().from(communityTopics).where(and(eq(communityTopics.id,id),eq(communityTopics.status,"published"))).limit(1);if(!topics[0])return Response.json({error:"Tópico não encontrado."},{status:404});const replies=await db.select().from(communityReplies).where(and(eq(communityReplies.topicId,id),eq(communityReplies.status,"published")));return Response.json({topic:topics[0],replies});}
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { if (process.env.COMMUNITY_ENABLED !== "true") return Response.json({ error: "Comunidade em breve." }, { status: 503 }); if (!sameOriginRequest(request)) return Response.json({ error: "Origem inválida." }, { status: 403 }); const auth=await requireApiUser(); if("error" in auth)return auth.error; const {id}=await params; const body=await request.json().catch(()=>({})); const validated=validateCommunityPost(body.title,body.body); if(validated.errors.length)return Response.json({errors:validated.errors},{status:400}); const db=getDb(); const rows=await db.select().from(communityTopics).where(and(eq(communityTopics.id,id),eq(communityTopics.authorEmail,auth.user.email))).limit(1); if(!rows[0])return Response.json({error:"Tópico não encontrado."},{status:404}); if(Date.now()-new Date(rows[0].createdAt).getTime()>30*60_000)return Response.json({error:"O prazo de edição terminou."},{status:403}); await db.update(communityTopics).set({title:validated.title,body:validated.body,updatedAt:new Date().toISOString()}).where(eq(communityTopics.id,id)); return Response.json({ok:true}); }
export async function DELETE(request: Request,{params}:{params:Promise<{id:string}>}){if(process.env.COMMUNITY_ENABLED!=="true")return Response.json({error:"Comunidade em breve."},{status:503});if(!sameOriginRequest(request))return Response.json({error:"Origem inválida."},{status:403});const auth=await requireApiUser();if("error" in auth)return auth.error;const {id}=await params;const now=new Date().toISOString();const result=await getDb().update(communityTopics).set({status:"removed",deletedAt:now,updatedAt:now}).where(and(eq(communityTopics.id,id),eq(communityTopics.authorEmail,auth.user.email))).returning({id:communityTopics.id});if(!result.length)return Response.json({error:"Tópico não encontrado."},{status:404});return Response.json({ok:true});}
