/* eslint-disable react-hooks/exhaustive-deps, @next/next/no-html-link-for-pages */
"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { normalizeSearch } from "@/lib/search";
type Topic={id:string;category:string;title:string;body:string;authorEmail:string;replyCount:number;createdAt:string};
export function CommunityClient({categories,userName}:{categories:string[];userName:string}){const[topics,setTopics]=useState<Topic[]>([]);const[query,setQuery]=useState("");const[sort,setSort]=useState<"recent"|"replied">("recent");const[open,setOpen]=useState(false);const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);
async function load(){setLoading(true);const response=await fetch("/api/community/topics");const data=await response.json();setTopics(data.topics||[]);setLoading(false)}useEffect(()=>{load()},[]);
const visible=useMemo(()=>topics.filter((topic)=>normalizeSearch(`${topic.title} ${topic.body} ${topic.category}`).includes(normalizeSearch(query))).sort((a,b)=>sort==="replied"?b.replyCount-a.replyCount:new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()),[topics,query,sort]);
async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setMessage("");const form=new FormData(event.currentTarget);const response=await fetch("/api/community/topics",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:form.get("title"),body:form.get("body"),category:form.get("category")})});const data=await response.json();if(!response.ok){setMessage(data.errors?.join(" ")||data.error||"Não foi possível publicar.");return}(event.target as HTMLFormElement).reset();setOpen(false);setMessage("Tópico publicado.");load()}
return <section className="community-shell"><div className="community-welcome"><div><span>Conectado como</span><strong>{userName}</strong></div><button onClick={()=>setOpen(!open)}>{open?"Fechar formulário":"Criar tópico"}</button></div>{open&&<form className="topic-form" onSubmit={submit}><label>Categoria<select name="category" required>{categories.map((item)=><option key={item}>{item}</option>)}</select></label><label>Título<input name="title" minLength={8} maxLength={120} required/></label><label>Contexto<textarea name="body" minLength={20} maxLength={4000} rows={6} required/></label><small>Máximo de dois links. Não publique dados pessoais.</small><button className="button primary" type="submit">Publicar tópico</button></form>}{message&&<p className="form-message" role="status">{message}</p>}<div className="community-tools"><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Pesquisar tópicos"/><select value={sort} onChange={(event)=>setSort(event.target.value as typeof sort)}><option value="recent">Mais recentes</option><option value="replied">Mais respondidos</option></select></div><div className="category-pills">{categories.map((item)=><button key={item} onClick={()=>setQuery(item)}>{item}</button>)}</div>{loading?<div className="empty-state"><strong>Carregando conversas…</strong></div>:visible.length?<div className="topic-list">{visible.map((topic)=><a href={`/comunidade/${topic.id}`} key={topic.id}><span>{topic.category}</span><div><strong>{topic.title}</strong><p>{topic.body}</p><small>{new Intl.DateTimeFormat("pt-BR").format(new Date(topic.createdAt))}</small></div><b>{topic.replyCount} respostas</b></a>)}</div>:<div className="empty-state"><strong>Nenhum tópico encontrado.</strong><p>Inicie uma conversa útil e contextualizada.</p></div>}</section>}

export function CommunityTopicClient({id,userName}:{id:string;userName:string}){const[topic,setTopic]=useState<Topic|null>(null);const[replies,setReplies]=useState<Array<{id:string;body:string;authorEmail:string;createdAt:string}>>([]);const[message,setMessage]=useState("");async function load(){const response=await fetch(`/api/community/topics/${id}`);const data=await response.json();setTopic(data.topic||null);setReplies(data.replies||[])}useEffect(()=>{load()},[id]);async function reply(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch(`/api/community/topics/${id}/replies`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body:form.get("body")})});const data=await response.json();if(!response.ok){setMessage(data.error||"Não foi possível responder.");return}(event.target as HTMLFormElement).reset();setMessage("Resposta publicada.");load()}if(!topic)return <div className="empty-state"><strong>Carregando tópico…</strong></div>;return <section className="topic-detail"><a href="/comunidade">← Voltar à comunidade</a><article className="topic-original"><span>{topic.category}</span><h1>{topic.title}</h1><p>{topic.body}</p><small>Publicado por {topic.authorEmail.replace(/(.{2}).+(@.+)/,"$1…$2")}</small></article><h2>{replies.length} respostas</h2><div className="replies-list">{replies.map((item)=><article key={item.id}><p>{item.body}</p><small>{item.authorEmail.replace(/(.{2}).+(@.+)/,"$1…$2")} · {new Intl.DateTimeFormat("pt-BR").format(new Date(item.createdAt))}</small></article>)}</div><form className="topic-form" onSubmit={reply}><label>Responder como {userName}<textarea name="body" minLength={4} maxLength={2000} rows={5} required/></label><button className="button primary">Publicar resposta</button></form>{message&&<p className="form-message">{message}</p>}</section>}
