/* eslint-disable @next/next/no-html-link-for-pages */
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { money, reviews } from "@/lib/site-data";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const review = reviews.find((item) => item.slug === slug); return review ? { title: review.name, description: review.summary, alternates: { canonical: `/reviews/${slug}` } } : { title: "Review não encontrado" }; }

export default async function ReviewPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const review = reviews.find((item) => item.slug === slug); if (!review) notFound();
  const total = review.pricePaid === null ? null : review.pricePaid + (review.repairCost || 0);
  const jsonLd = { "@context": "https://schema.org", "@type": "Review", itemReviewed: { "@type": "Product", name: review.name, brand: review.manufacturer }, reviewBody: review.summary, author: { "@type": "Organization", name: "Imports Tech" }, datePublished: review.testedAt };
  return <main id="conteudo" className="page-main detail-page"><nav className="breadcrumbs" aria-label="Trilha de navegação"><a href="/">Início</a><span>/</span><a href="/reviews">Reviews</a><span>/</span><span>{review.name}</span></nav><header className="detail-hero"><div><span className="content-tag">{review.manufacturer} · {review.category}</span><h1>{review.name}</h1><p>{review.summary}</p></div><span className={`verdict large ${review.verdict === "Vale a pena" ? "positive" : "conditional"}`}>{review.verdict}</span></header><section className="detail-facts"><div><span>Testado em</span><strong>{new Intl.DateTimeFormat("pt-BR").format(new Date(review.testedAt))}</strong></div><div><span>Preço pago</span><strong>{money(review.pricePaid)}</strong></div><div><span>Custo de reparo</span><strong>{money(review.repairCost)}</strong></div><div><span>Custo total conhecido</span><strong>{money(total)}</strong></div></section><section className="pros-cons"><div><span className="eyebrow-v2">PONTOS POSITIVOS</span><ul>{review.positives.map((item) => <li key={item}>+ {item}</li>)}</ul></div><div><span className="eyebrow-v2">PONTOS DE ATENÇÃO</span><ul>{review.negatives.map((item) => <li key={item}>− {item}</li>)}</ul></div></section><section className="scores-section"><div><span className="eyebrow-v2">NOTAS DO TESTE</span><h2>{review.scores ? "Desempenho por categoria" : "Avaliação em consolidação"}</h2><p>{review.scores ? "Notas baseadas no teste editorial do canal." : "As notas numéricas ainda não foram publicadas pelo canal. Elas não serão estimadas ou inventadas."}</p></div>{review.scores && <div className="score-grid">{Object.entries(review.scores).map(([key,value]) => <div key={key}><span>{key}</span><strong>{value}/10</strong></div>)}</div>}</section><section className="current-status"><span>O que aconteceu depois?</span><h2>{review.status}</h2><p>Última atualização editorial: {new Intl.DateTimeFormat("pt-BR").format(new Date(review.updatedAt))}.</p><a className="button primary" href={`https://youtu.be/${review.videoId}`} target="_blank" rel="noreferrer">▶ Assistir ao vídeo relacionado</a></section><div className="affiliate-note">Este conteúdo pode receber links de afiliado no futuro. Quando isso acontecer, o aviso será exibido antes do link e não alterará o veredito editorial.</div><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}/></main>;
}
